"""Optional stateless presentation helpers for MARL-BattleGrounds."""

from marl_battlegrounds.rendering.geometry import (
    RenderResult,
    draw_geometry,
    redraw_geometry,
    render_geometry,
)
from marl_battlegrounds.rendering.visuals import (
    ActivationVisual,
    AuraCueVisual,
    BattlefieldOverlays,
    ChargeTrailVisual,
    HealthDeltaVisual,
    LaneMarkerVisual,
    ObserverVisibilityVisual,
    PersistentEffectVisual,
    RangeVisual,
    RejectedActionVisual,
    SelectionVisual,
    StatusCueVisual,
    TargetLinkVisual,
    class_color,
    describe_snapshot_overlays,
    merge_battlefield_overlays,
    source_effect_color,
    team_color,
)

__all__ = [
    "ActivationVisual",
    "AuraCueVisual",
    "BattlefieldOverlays",
    "ChargeTrailVisual",
    "HealthDeltaVisual",
    "LaneMarkerVisual",
    "ObserverVisibilityVisual",
    "PersistentEffectVisual",
    "RangeVisual",
    "RejectedActionVisual",
    "RenderResult",
    "SelectionVisual",
    "StatusCueVisual",
    "TargetLinkVisual",
    "class_color",
    "describe_snapshot_overlays",
    "draw_geometry",
    "merge_battlefield_overlays",
    "redraw_geometry",
    "render_geometry",
    "source_effect_color",
    "team_color",
]
