"""Generate the compact browser schema for authorized presentation V1 frames.

The browser owns the validation algorithm, while Python remains the source of
truth for the closed five-leaf structural contract.  This exporter deliberately
removes documentation-only JSON Schema metadata so the runtime asset contains
only validation-relevant keywords.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import cast

from scripts.dev.visual_debugger.presentation_protocol import (
    _AUTHORIZED_PRESENTATION_FRAME_ADAPTER,  # pyright: ignore[reportPrivateUsage]
)

type JsonValue = (
    None | bool | int | float | str | list[JsonValue] | dict[str, JsonValue]
)

_DOCUMENTATION_KEYS = frozenset({"description", "title"})
_SCHEMA_KEYWORDS = frozenset(
    {
        "$defs",
        "$ref",
        "additionalProperties",
        "anyOf",
        "const",
        "description",
        "discriminator",
        "enum",
        "exclusiveMaximum",
        "exclusiveMinimum",
        "items",
        "maxItems",
        "maxLength",
        "maximum",
        "minItems",
        "minLength",
        "minimum",
        "oneOf",
        "pattern",
        "prefixItems",
        "properties",
        "required",
        "title",
        "type",
    }
)


def _validate_schema_keywords(value: object, *, context: str = "schema") -> None:
    if isinstance(value, list):
        for item in cast("list[object]", value):
            _validate_schema_keywords(item, context="schema")
        return
    if not isinstance(value, dict):
        return
    record = cast("dict[str, object]", value)
    if context in {"names", "mapping"}:
        for item in record.values():
            if context == "names":
                _validate_schema_keywords(item, context="schema")
        return
    unknown = set(record).difference(_SCHEMA_KEYWORDS)
    if unknown:
        raise ValueError(
            f"unsupported authorized-presentation schema keywords: {unknown}"
        )
    for key, item in record.items():
        if key in {"$defs", "properties"}:
            _validate_schema_keywords(item, context="names")
        elif key == "discriminator":
            if not isinstance(item, dict):
                raise ValueError("unsupported presentation discriminator schema")
            discriminator = cast("dict[str, object]", item)
            if set(discriminator).difference({"mapping", "propertyName"}):
                raise ValueError("unsupported presentation discriminator schema")
            mapping = discriminator.get("mapping")
            if mapping is not None:
                _validate_schema_keywords(mapping, context="mapping")
        elif key not in {"required", "enum"}:
            _validate_schema_keywords(item, context="schema")


def _compact_schema(value: object, *, preserve_names: bool = False) -> JsonValue:
    if isinstance(value, dict):
        record = cast("dict[str, object]", value)
        return {
            key: _compact_schema(
                item,
                preserve_names=key in {"$defs", "properties", "mapping"},
            )
            for key, item in record.items()
            if preserve_names or key not in _DOCUMENTATION_KEYS
        }
    if isinstance(value, list):
        return [_compact_schema(item) for item in cast("list[object]", value)]
    if value is None or isinstance(value, bool | int | float | str):
        return value
    raise TypeError("JSON Schema contains a non-JSON value")


def render_browser_schema_module() -> str:
    """Return one deterministic JavaScript module containing the exact schema."""
    source_schema = _AUTHORIZED_PRESENTATION_FRAME_ADAPTER.json_schema()
    _validate_schema_keywords(source_schema)
    schema = _compact_schema(source_schema)
    encoded = json.dumps(schema, ensure_ascii=True, separators=(",", ":"))
    encoded_literal = json.dumps(encoded, ensure_ascii=True)
    return (
        "// Generated by export_authorized_presentation_browser_schema.py.\n"
        "// Do not edit by hand.\n"
        "// @ts-nocheck -- generated JSON Schema is validated by its consumer.\n"
        "function freezeGeneratedSchema(value) {\n"
        '  if (value && typeof value === "object") {\n'
        "    for (const child of Object.values(value)) freezeGeneratedSchema(child);\n"
        "    Object.freeze(value);\n"
        "  }\n"
        "  return value;\n"
        "}\n"
        "export const AUTHORIZED_PRESENTATION_SCHEMA_V1 = "
        f"freezeGeneratedSchema(JSON.parse({encoded_literal}));\n"
    )


def main() -> None:
    repository_root = Path(__file__).resolve().parents[3]
    destination = (
        repository_root
        / "web"
        / "visual_debugger"
        / "src"
        / "authorized-presentation-schema.js"
    )
    destination.write_text(render_browser_schema_module(), encoding="utf-8")


if __name__ == "__main__":
    main()
